# Generated by Django 3.0.8 on 2020-07-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditprogramm',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
